### ISSUE TITLE
Describe development workflow

### ISSUE THREAD

**Issue by alexanderkjeldaas** [freebroccolo/docker-haskell#17]
It would be great if various development workflows would be described in the documentation for the docker image.   For example, how to integrate `docker build` into `haskell-mode` in emacs, an opinion on whether using docker for development will slow me down wrt other options, etc.

**Comment by ChristopherBiscardi** [comment]
## My typical approach:

#### dev container

I usually have a "development" docker image that includes my emacs, zsh, etc and builds off `haskell:7.8`. It's typically a `docker pull biscarch/emacs` away from any new system.

My dev image: [github](https://github.com/ChristopherBiscardi/docker-emacs) (or as `docker pull biscarch/emacs`).

The dev image has `haskell-mode` and `stylish-haskell`, but not `structured-haskell-mode` or `company-ghc`, etc (yet). Then I use [this shell function](https://gist.github.com/ChristopherBiscardi/49c3d42f922853966824) to boot emacs in a container in either the `pwd` or root of the `.git` repo. Alternatively, I can boot into `zsh` if I'm trying to do stuff outside of emacs.

#### project container

Then I have a dockerfile for the project in the root, typically with a `CMD` that runs the project. After building this image you can run a more complete `ghci` session or just run the webserver, etc.

#### production image

The other thing I've been playing with is a production container, which is just `debian:jessie` + `libgmp`.  Then I copy my binary out of the `project` image and put it in the `production` image. This is a more involved flow that isn't really necessary, but produces a tighter final image.

## fin

If this is useful I could try to clean it up a bit and write it up. Right now it's sort of "what works for me", but I'd be happy to get some feedback, write some READMEs, etc.

What other approaches were you thinking of?
