### ISSUE TITLE
7.8.4

### ISSUE THREAD

**Issue by gregwebs** [freebroccolo/docker-haskell#20]
7.8.4 has been out for quite some time now and is more stable than 7.8.3. I tried to modify the Dockerfile to install 7.8.4 but ran into problems.

```
W: Failed to fetch http://deb.haskell.org/stable/./Release.gpg  Cannot initiate the connection to deb.haskell.org:80 (2001:4801:7824:101:b6d8:5ee5:ff11:5e07). - connect (101: Network is unreachable) [IP: 2001:4801:7824:101:b6d8:5ee5:ff11:5e07 80]

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
E: Unable to locate package ghc-7.8.4
E: Couldn't find any package by regex 'ghc-7.8.4'
2015/03/22 09:02:21 The command [/bin/sh -c apt-get
```

**Comment by md5** [comment]
It looks like deb.haskell.org is down: http://www.downforeveryoneorjustme.com/http://deb.haskell.org/stable/

**Comment by md5** [comment]
cf. https://status.haskell.org/

> February 25, 2015 4:00PM CST / February 25, 2015 10:00PM UTC
> [Investigating] deb.haskell.org remains down while we discuss restoring functionality.

**Comment by ChristopherBiscardi** [comment]
Yes, I was re-attempting this yesterday, but since deb.haskell.org has been down (since Feb) it obviously failed.

We could switch the base image to Ubuntu, which would allow us to use a ppa but a better solution may be switching to installing from [downloads.haskell.org](http://downloads.haskell.org/~ghc/7.8.4/) for `7.8.4`. (I'll look into this)

**Comment by md5** [comment]
@nomeata I believe you run deb.haskell.org from what I could glean. Hope you don't mind me pinging you for your opinion here.

**Comment by nomeata** [comment]
Ah, there are users of deb.haskell.org? That’s news to us... :-)

I don’t know when deb.haskell.org will be back, that’s up to admin@haskell.org. You can indicate interest, though...

**Comment by ChristopherBiscardi** [comment]
thanks @nomeata 

I sent an email. If it doesn't look like deb.haskell.org will be up in a timely manner, Using [hvr's ppa](https://launchpad.net/~hvr/+archive/ubuntu/ghc) as described [here](https://github.com/bitemyapp/learnhaskell#debian) seems to be the best solution going forward.

**Comment by psftw** [comment]
Even if the Debian repo comes back up, will it have the latest version 7.10.1 just released?  How about 7.8.4?  Before it went down, it still had 7.8.3, so we were stuck in this situation anyway.  In the past week 7.10.1 was released and is really the only supported version now, but we could probably convince the official image powers that be to accept a three month late 7.8.4 tag.

I resurrected my haskell Dockerfiles + hacky tests and put them back up at https://github.com/psftw/docker-haskell. These are based on upstream release binaries designed for deb7, which seem to be better supported and released in tandem with GHC releases.  The downside of these is that they still need alex/happy and are huge in comparison:

    $ docker images haskell
    REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
    haskell             7.8.3               c0a54a2c768a        9 hours ago         1.675 GB
    haskell             7.10.1              6e0de97b397b        9 hours ago         1.817 GB
    haskell             7.8.4               f3b9a46aced8        10 hours ago        1.799 GB
    haskell             latest              bc0206a9b75f        8 weeks ago         601.4 MB
    haskell             7.8                 bc0206a9b75f        8 weeks ago         601.4 MB


I'm not sure why they are so big or how much fat could be trimmed.  Anyhow, just another idea/option if there is interest.  It looks like the PPA mentioned above is up to date, and at least semi-official based on who is maintaining it.

**Comment by md5** [comment]
It looks like there are a bunch of files like `/usr/local/lib/ghc-7.10.1/ghc_EMlWrQ42XY0BNVbSrKixqY/libHSghc-7.10.1-EMlWrQ42XY0BNVbSrKixqY_p.a` in there that seem to be temp files. I'm not sure why `make install` would copy those out of `/usr/src/ghc`.

**Comment by psftw** [comment]
Yup, strange those were included.  They appear to be archives of object files, which are totally unnecessary.  I need to find out more about the configure/install options for the binary releases.  I see other things such as docs that could be disabled as well.

**Comment by md5** [comment]
@psftw Any chance you could rebase that against this repo to get a shared ancestor?

**Comment by ChristopherBiscardi** [comment]
@psftw #21 is probably relevant if we're going to switch to your dockerfiles.

**Comment by psftw** [comment]
@md5 I don't think that would make sense as it's totally different history, and I'm not convinced it is the best solution to the problem yet either.
@ChristopherBiscardi cool, I've somehow missed that ping and that issue altogether.  I will check it out for sure, and I can hit both methodologies with the same test scripts from my GH repo.

**Comment by ChristopherBiscardi** [comment]
tags `7.8` and `7.8.4` are now on the registry.

`7.10.1`, `7.10`, `7`, `latest` now point to 7.10 as well.

Please file issues if you encounter difficulties with the new tags.

**Comment by gregwebs** [comment]
Thank you! I just upgraded.
