### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by ftomassetti** [freebroccolo/docker-haskell#24]
Running the suggested command:

```
docker run -it --rm haskell:7.10
```

I got:
```
Unable to find image 'haskell:7.10' locally
Pulling repository haskell
FATA[0005] Tag 7.10 not found in repository haskell
```

Running:

```
docker run -it --rm haskell:latest
```

Works fine

**Comment by md5** [comment]
It's not that the `README` is outdated, but rather that `haskell:7.10` hasn't been pushed yet.

See docker-library/official-images#651

**Comment by ChristopherBiscardi** [comment]
7:10 has been pushed. Closing this.
