### ISSUE TITLE
No C++ compiler included?

### ISSUE THREAD

**Issue by eightyeight** [freebroccolo/docker-haskell#34]
As noted in bos/double-conversion#11, it's necessary to install `g++` inside the container before being able to compile the `double-conversion` library. Is this something that should be included in the base Docker image? I encountered this issue again when trying to compile an example with Servant.

**Comment by ChristopherBiscardi** [comment]
Looking into this now. If it's preventing Servant from installing we should probably include it.

**Comment by ChristopherBiscardi** [comment]
@eightyeight Can you check to make sure https://github.com/freebroccolo/docker-haskell/pull/35 solves your issue?
