### ISSUE TITLE
Add support for 7.10.3

### ISSUE THREAD

**Issue by centromere** [freebroccolo/docker-haskell#42]
Support for 7.10.3 would be greatly appreciated.

**Comment by ChristopherBiscardi** [comment]
7.10.3 was [merged to master](https://github.com/freebroccolo/docker-haskell/pull/41). 

@psftw Are you waiting on anything to submit to the official images repo?

**Comment by psftw** [comment]
I'm putting together some doc updates (to mention Stack) and will submit ASAP.  Sorry for the huge delay on this update.

**Comment by psftw** [comment]
PRs for official image and doc updates: https://github.com/docker-library/official-images/pull/1392 https://github.com/docker-library/docs/pull/472

**Comment by ChristopherBiscardi** [comment]
:+1:
