### ISSUE TITLE
Add an example for Dockerfile using Stack

### ISSUE THREAD

**Issue by nightscape** [freebroccolo/docker-haskell#43]
Hi all,

I'm a Haskell noob and I'm trying to build the Unison project (which recently switched to stack) in Docker (old PR and discussion [here](https://github.com/unisonweb/platform/pull/32)).
I'm quite proficient with Docker, but not at all with stack or cabal.
What I'm trying to achieve is a build that caches dependencies before starting the compilation of the actual Unison code.

Am I right to assume that the best way to do that is something like this?
```
ADD shared/unison-shared.cabal /opt/unison/shared/unison-shared.cabal
ADD node/unison-node.cabal /opt/unison/node/unison-node.cabal
ADD editor/unison-editor.cabal /opt/unison/editor/unison-editor.cabal
RUN stack exec -- cabal exec -- cd node && cabal install --only-dependencies -j4 && cd ../shared && cabal install --only-dependencies -j4 && cd ../editor && cabal install --only-dependencies -j4
```

Could you provide a version of the snap 7.10 example that shows how to achieve the same thing using stack?

Thanks!
   Martin

**Comment by ChristopherBiscardi** [comment]
You will need the 7.10.2 image (according to the unison project's stack config). Unfortunately the Official Image for 7.10.2 doesn't include stack, so you will need to create a derivative image which includes `stack`:

```
FROM haskell:7.10.2

RUN echo 'deb http://download.fpcomplete.com/debian/jessie stable main'| tee /etc/apt/sources.list.d/fpco.list && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C5705533DA4F78D8664B5DC0575159689BEFB442 && \
    apt-get update && \
    apt-get install -y --no-install-recommends stack
```

Using this and adding some project-specific commands mostly worked except for an extra-dep (`applicative-extras`) which stack seems to be choking on. Note that I cloned the unison repo into `./platform` on my host.

```
FROM haskell:7.10.2

RUN echo 'deb http://download.fpcomplete.com/debian/jessie stable main'| tee /etc/apt/sources.list.d/fpco.list && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C5705533DA4F78D8664B5DC0575159689BEFB442 && \
    apt-get update && \
    apt-get install -y --no-install-recommends stack

COPY ./platform /opt/unison/

WORKDIR /opt/unison/
RUN stack build unison-node
```

```
unison-node-0.1: build
Preprocessing library unison-node-0.1...
/usr/bin/ld: cannot find -lHSapplicative-extras-0.1.8-GuDuiiwMTTVLsSgJqNym44-ghc7.10.2
collect2: error: ld returned 1 exit status
Completed 82 action(s).

--  While building package unison-node-0.1 using:
      /root/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.4.0-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0 build lib:unison-node exe:node --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

**Comment by nightscape** [comment]
Hi @ChristopherBiscardi, thanks for looking into this!
I had the build working at one point using `samdoshi/haskell-stack` as base image and a Dockerfile similar to the one you worked out.
The problem with this approach is that if you change only one line in any file, the Docker cache will be busted and all your dependencies have to be downloaded and compiled again. Therefore I would have liked to first just copy the `.cabal` files and tell stack to only download and compile the dependencies without trying to compile the actual sources (which would fail because the corresponding files were not `ADD`ed yet). The [snap 7.10 example](https://github.com/freebroccolo/docker-haskell/blob/master/examples/7.10/snap/Dockerfile) shows how to achieve this using cabal and I'm wondering what's the way to do the same thing with stack...

**Comment by nightscape** [comment]
@ChristopherBiscardi I ran into the same problem you did with applicative-extras. After I put `.stack-works` into the `.dockerignore` file things worked better.
To answer my own question, something like the following should work:
```
ADD shared/unison-shared.cabal /opt/unison/shared/unison-shared.cabal
ADD node/unison-node.cabal /opt/unison/node/unison-node.cabal
ADD editor/unison-editor.cabal /opt/unison/editor/unison-editor.cabal
RUN stack build --only-dependencies
ADD . /opt/unison
RUN stack build unison-node
```
If all works well, I'll create a PR for another snap 7.10 example using stack.
