### ISSUE TITLE
Ship GHC 8.0

### ISSUE THREAD

**Issue by ChristopherBiscardi** [freebroccolo/docker-haskell#45]
I have 8.0.1 working locally. Putting this here to remind myself to push later

**Comment by ocramz** [comment]
@ChristopherBiscardi any news on 8.0.1 ;)

**Comment by ChristopherBiscardi** [comment]
@ocramz https://github.com/freebroccolo/docker-haskell/pull/47

Just need to update the hashes and submit a PR to official

**Comment by ChristopherBiscardi** [comment]
Official Images PR is https://github.com/docker-library/official-images/pull/1848

**Comment by ChristopherBiscardi** [comment]
Closing since the PR was merged. Thanks @ocramz

**Comment by ocramz** [comment]
Thanks to you @ChristopherBiscardi  !
