### ISSUE TITLE
Stack cannot find ghc when building 8.0 example

### ISSUE THREAD

**Issue by DStranger** [freebroccolo/docker-haskell#51]
I am trying to run the example servant-api app for 8.0 image and keep getting the following error:
```
docker build .
Sending build context to Docker daemon 15.36 kB
Step 1/5 : FROM haskell:8
8: Pulling from library/haskell
...
No compiler found, expected minor version match with ghc-8.0.1 (x86_64) (based on resolver setting in /opt/servant-api/stack.yaml).
To install the correct GHC into /root/.stack/programs/x86_64-linux/, try running "stack setup" or use the "--install-ghc" flag. To use your system GHC installation, run "stack config set system-ghc --global true", or use the "--system-ghc" flag.
```
Am I doing something wrong?

**Comment by ChristopherBiscardi** [comment]
Looks like docker inc rebuilt the haskell images about 2 weeks ago and when they did that stack updated. It looks like stack changed something breaking between these versions. I'll have to look into the fix later.

```
> docker images | ack haskell
haskell                               8                   3fc5a5260db0        13 days ago         994 MB
haskell                               <none>              5f974c5f08c2        2 months ago        991 MB
```

<img width="745" alt="screen shot 2017-01-30 at 10 18 01 am" src="https://cloud.githubusercontent.com/assets/551247/22435609/8e16e058-e6d5-11e6-8e6d-f7fd02dac3cb.png">

**Comment by cdupont** [comment]
@ChristopherBiscardi great, thanks! I'm having the problem too.

**Comment by DStranger** [comment]
@ChristopherBiscardi 
From stack's 1.3.0 changelog:
> Stack will now always use its own GHC installation, even when a suitable GHC installation is available on the PATH. To get the old behaviour, use the --system-ghc flag or run stack config set system-ghc --global true. 

So, `RUN stack config set system-ghc --global true` will fix the problem, but maybe specifying stack version explicitly would also be a good idea.
