### ISSUE TITLE
How to use cache with Stack

### ISSUE THREAD

**Issue by cdupont** [freebroccolo/docker-haskell#54]
Hi there,
how to enable cache with Stack?
I have the following Dockerfile:
```
FROM haskell:8.0.1

COPY . /opt/foo
WORKDIR /opt/foo
RUN stack install --system-ghc

ENV PATH /usr/bin:$PATH
ENTRYPOINT ["stack exec foo --system-ghc"]
```

But each time I do `docker build -t cdupont/nomyx .` it will redo everything, including recompiling all stack packages, which is very long.

**Comment by chrissound** [comment]
You would probably have to build an image with the cache "filled" for stack.

**Comment by psftw** [comment]
Sorry it's been a while, but in case you were still looking for help on this.... 

Essentially the `COPY . /opt/foo` line in your example will cause the `docker build` command to re-execute that step whenever it detects changes to any files in the folder.  Instead, what you likely want to do is COPY just the `.cabal` and `stack.yaml` files and `RUN stack install --only-dependencies` first.

A gist that shows this caching in action: https://gist.githubusercontent.com/psftw/74e310e911d83518af37958912ca5090/raw/253ef3c4fa8e23fc5080d731f2827ad0a85448d9/gistfile1.txt

**Comment by cdupont** [comment]
@psftw thanks, that's what I wanted.
