### ISSUE TITLE
[8.2.1] LLVM 3.9 is missing

### ISSUE THREAD

**Issue by carbolymer** [freebroccolo/docker-haskell#64]
I am trying to build my project using stack, and I am getting the following error:
```
<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM 3.9
ghc: could not execute: opt
Completed 126 action(s).
```

Please consider using newer version of debian instead of jessie.

**Comment by psftw** [comment]
We don't ship the LLVM toolchain in the image as it is an optional backend.  It could be added in a derived image.

**Comment by psftw** [comment]
Also sorry for the insane delay in responding here! :clock10: :cry:
