### ISSUE TITLE
Could not find module ‘Servant.API.Flatten’: There are files missing in the ‘servant-flatten-0.2’ package

### ISSUE THREAD

**Issue by cdupont** [freebroccolo/docker-haskell#83]
Hello,
I try to compile my program in a docker container with this Dockerfile:
```
FROM haskell:8.4

COPY stack.yaml   /opt/waziup/stack.yaml
COPY foo.cabal /opt/waziup/foo.cabal

WORKDIR /opt/waziup
RUN stack setup
RUN stack install --only-dependencies

COPY .  /opt/waziup
RUN stack install
```

My stack.yaml file is like this:
```
resolver: lts-12.20
extra-deps:
 - servant-flatten-0.2
packages:
 - '.'
```
This works when I type `stack install`. However when I try to compile the docker:
```
$ docker build .
...
servant-flatten-0.2: download
servant-flatten-0.2: configure
servant-flatten-0.2: build
servant-flatten-0.2: copy/register
...
    /opt/waziup/src/Foo.hs:37:1: error:
        Could not find module ‘Servant.API.Flatten’
        There are files missing in the ‘servant-flatten-0.2’ package,
        try running 'ghc-pkg check'.
        Use -v to see a list of the files searched for.
```
Any idea? What happens with the extra-deps package?

**Comment by psftw** [comment]
I may not be that helpful, but a couple of thoughts: If you can successfully "stack install" outside of the docker context, think about what environment differences could have a potential impact and validate.  What versions of tools are you using on what OS, etc.

**Comment by psftw** [comment]
closing due to staleness
