### ISSUE TITLE
Huge image

### ISSUE THREAD

**Issue by cdupont** [freebroccolo/docker-haskell#86]
Hello,
I'm compiling an image based on this repo. Here is my Dockerfile:

```
FROM haskell:8.4

COPY stack.yaml   /opt/waziup/stack.yaml
COPY waziup.cabal /opt/waziup/waziup.cabal
COPY aesonbson/ /opt/waziup/aesonbson
COPY servant-flatten/ /opt/waziup/servant-flatten
COPY keycloak-hs/ /opt/waziup/keycloak-hs

RUN apt-get update
RUN apt-get --assume-yes install liblzma-dev

WORKDIR /opt/waziup
RUN stack setup
RUN stack install --only-dependencies 

COPY src /opt/waziup/src
COPY data /opt/waziup/data
COPY Setup.hs /opt/waziup/Setup.hs
RUN stack install --fast 

ENV PATH /usr/bin:$PATH
CMD stack exec --system-ghc -- waziup-servant 

EXPOSE 8081
```
The resulting image is 7 Go... Is there anything wrong in my Dockerfile?
Thanks a lot

**Comment by cdupont** [comment]
I simplified the Dockerfile to this:
```
FROM haskell:8.6

COPY . /opt/waziup
WORKDIR /opt/waziup

RUN apt-get update && apt-get --assume-yes install liblzma-dev

RUN stack build --fast

CMD stack exec waziup-servant 

EXPOSE 8081
```
However, the image is still 4.7 Go...

**Comment by hanjoosten** [comment]
You probably seen [this documentation](https://docs.haskellstack.org/en/stable/docker_integration/#cleanup-clean-up-old-images-and-containers), but just in case you missed it. Good luck.

**Comment by cdupont** [comment]
It seems that multi-stage builds are the solution:
https://docs.docker.com/develop/develop-images/multistage-build/

```
#Build stage
FROM haskell:8.6 as build

COPY . /opt/waziup
WORKDIR /opt/waziup

RUN apt-get update && apt-get --assume-yes install liblzma-dev

RUN stack build --fast

# Deploy stage
FROM ubuntu

WORKDIR /opt/waziup
COPY --from=build /opt/waziup/.stack-work/install/x86_64-linux/lts-13.5/8.6.3/bin/waziup-servant .
COPY data /opt/waziup/data
ENV PATH /usr/bin:$PATH
CMD /opt/waziup/waziup-servant 

EXPOSE 8081
```
The deploy stage will restart from a scratch image and copy over only the built executable.
More infos here for Stack:
https://www.fpcomplete.com/blog/2017/12/building-haskell-apps-with-docker

**Comment by psftw** [comment]
The base `haskell:X.Y` image is going to remain on the larger side because we want to support various common use cases out of the box. Using a multistage build in your case seems reasonable.  In the past I've explored creating a '-slim' variant, but came away with the impression that it wasn't worth the effort.  Open to ideas if the situation has changed.

**Comment by cdupont** [comment]
Agreed. Multistage seems to be want I was looking for... Closing
