### ISSUE TITLE
GHC 8.6.4

### ISSUE THREAD

**Issue by adamschoenemann** [freebroccolo/docker-haskell#87]
Thanks for providing these images :)
I'm just opening this issue to notify you of the [release of GHC 8.6.4](https://ghc.haskell.org/trac/ghc/blog/ghc-8.6.4-released).
It seems that it is still not available in the [debian repo](https://downloads.haskell.org/debian/) so I guess updating the docker image will be more involved until that happens.
If anyone knows how to speed up the process (if possible) of getting it to the debian repo I'd appreciate the help :)

**Comment by adamschoenemann** [comment]
Meanwhile, this can be used instead to use ghc 8.6.4 (use at own risk!):
```
## Dockerfile for a haskell environment
## Ideally we'd use the one from docker-hub but it doesn't have 8.6.4 yet
FROM       debian:stretch

## ensure locale is set during build
ENV LANG            C.UTF-8


RUN apt-get update && \
    apt-get install -y --no-install-recommends gnupg ca-certificates dirmngr curl git && \
    echo 'deb http://downloads.haskell.org/debian stretch main' > /etc/apt/sources.list.d/ghc.list && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA3CBA3FFE22B574 && \
    apt-get update && \
    apt-get install -y --no-install-recommends cabal-install-2.4 \
        zlib1g-dev libtinfo-dev libsqlite3-dev g++ netbase xz-utils make libgmp-dev tar wget && \
    wget https://downloads.haskell.org/ghc/8.6.4/ghc-8.6.4-x86_64-deb9-linux.tar.xz && \
    tar xf ghc-8.6.4-x86_64-deb9-linux.tar.xz && \
    cd ghc-8.6.4 && \
    ./configure --prefix=/opt/ghc/8.6.4 && \
    make install && \
    cd .. && \
    curl -fSL https://github.com/commercialhaskell/stack/releases/download/v1.9.3/stack-1.9.3-linux-x86_64.tar.gz -o stack.tar.gz && \
    curl -fSL https://github.com/commercialhaskell/stack/releases/download/v1.9.3/stack-1.9.3-linux-x86_64.tar.gz.asc -o stack.tar.gz.asc && \
    export GNUPGHOME="$(mktemp -d)" && \
    echo "disable-ipv6" >> "$GNUPGHOME/dirmngr.conf" && \
    gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys C5705533DA4F78D8664B5DC0575159689BEFB442 && \
    gpg --batch --verify stack.tar.gz.asc stack.tar.gz && \
    tar -xf stack.tar.gz -C /usr/local/bin --strip-components=1 && \
    /usr/local/bin/stack config set system-ghc --global true && \
    /usr/local/bin/stack config set install-ghc --global false && \
    rm -rf "$GNUPGHOME" /var/lib/apt/lists/* /stack.tar.gz.asc /stack.tar.gz

ENV PATH /root/.cabal/bin:/root/.local/bin:/opt/cabal/2.4/bin:/opt/ghc/8.6.4/bin:$PATH

## run ghci by default unless a command is specified
CMD ["ghci"]
```

**Comment by adinapoli-mndc** [comment]
@freebroccolo any way we could help expediting this one? It would indeed be nice to have `8.6.4` out 😉

**Comment by gromakovsky** [comment]
Btw, GHC 8.6.5 was released in April.

**Comment by gromakovsky** [comment]
I see that the relevant MR was merged 15 hours ago. Does it mean that 8.6.4 will be available from Docker Hub soon?

**Comment by psftw** [comment]
There is a separate PR process to the downstream official images project to get the new images published. I think we should skip 8.6.4 and go straight to 8.6.5 before publishing at this point. The PR that was merged yesterday doesn't version bump the Stack tool either, and there are some validation tests I'd like to run as well.. I ran in to some new potential issues when I tested out a 8.6.5 image earlier this week, but got distracted with other things. Sorry for the delay.  I expect to have updated images read to go tomorrow when I'll have time to dig in.

**Comment by psftw** [comment]
Addressed via https://github.com/freebroccolo/docker-haskell/commit/7fd359b8dab3bf543832eb1ff34e1a46eef262a7 
(albeit very late because I'm a horrible person)

**Comment by psftw** [comment]
Downstream PR which is the last hurdle to publication on DockerHub: https://github.com/docker-library/official-images/pull/5928

**Comment by adinapoli-mndc** [comment]
Yay, thank you!
