### ISSUE TITLE
Haskell Code Scan - Critical Vulnerabilities

### ISSUE THREAD

**Issue by hallmont** [freebroccolo/docker-haskell#89]
Hi,

Are there any plans to resolve the Critical vulnerabilities in the code scan ?  My company would like to use the haskell docker image, but would not approve its use without the Critical vulnerabilities resolved.

Thanks!

-- John

**Comment by GrahamCampbell** [comment]
Could you link to where the code scan is visible please. I can't see it on the hub?

**Comment by GrahamCampbell** [comment]
Oh, I have to login to see... stupid website design!

**Comment by GrahamCampbell** [comment]
I think this is going to be a no fix, because the base image this depends on "debian:stretch" has "vulnerabilities", even the latest one.

You sayyour company won't approve it. Do you use any docker images at all then, since anything debian-based will be marked as having vulnerabilities?

**Comment by hallmont** [comment]
Okay, if the critical vulnerability is only in the base Linux OS, then you can close this issue.  We will try to create a docker image based on Red Hat.

**Comment by GrahamCampbell** [comment]
I wouldn't be suprised if the Red Hat images had the exact same vulnerable libraies tbh.

**Comment by psftw** [comment]
I used to be able to review the CVE data produced by DockerHub, but I don't see it anymore (?). Maybe "Official Images" are no longer scanned automatically? Also, there is a paradigm out there to support multiple base OS with different tags, though RHEL is not really going to be an option due to licensing. Debian is also easier to implement due to upstream packagers handling most of the work for us.

**Comment by GrahamCampbell** [comment]
Has the possibility of an alpine-based image been explored? Many of the other official docker imagez offer both alpine and debian-based images.

**Comment by hallmont** [comment]
Actually, looks like our company requires an internal RH base, so I wouldn't be able to use from Docker Hub after all.  What about CentOS ?  How popular is it as a base image ?

**Comment by hallmont** [comment]
Any chance someone can provide the current Dockerfile ?  I can try it out with my base image.
