### ISSUE TITLE
Install ssh in the image

### ISSUE THREAD

**Issue by Sir4ur0n** [freebroccolo/docker-haskell#90]
Hi,

As Stack needs SSH when using an `extra-deps` from a Git repository (see [Stack documentation](https://docs.haskellstack.org/en/stable/yaml_configuration/#extra-deps)) and `ssh` is not available in the image, I think it would make sense to install it, what do you think about it?

**Comment by Sir4ur0n** [comment]
By the way if you are ok with this, I can open a PR, it should be simple enough 😅

**Comment by psftw** [comment]
Sounds reasonable to me, and PRs are welcome. I take it that SSH is required for ssh:// git references?

**Comment by psftw** [comment]
I built and tested an image with openssh-client installed, but I've held off on merging it until I can see it in action and write a simple test to validate the functionality going forward.

**Comment by TD5** [comment]
@psftw, how are your tests for this looking? Similarly to @Sir4ur0n, I am keen to see this change land. Thanks for all of your contributions ☺️

**Comment by Sir4ur0n** [comment]
Hey, sorry for replying so late :sweat_smile: 

> I take it that SSH is required for ssh:// git references?

You are absolutely correct.

Would you mind providing steps to build the image?

I tried with both 8.8 and 8.6 and I get the same error:
```bash
$ docker build .

<a lot of logs>

Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.IET7tfyeeF/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys BA3CBA3FFE22B574
gpg: keyserver receive failed: No keyserver available
The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends gnupg ca-certificates dirmngr curl git &&     echo 'deb http://downloads.haskell.org/debian stretch main' > /etc/apt/sources.list.d/ghc.list &&     apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA3CBA3FFE22B574 &&     apt-get update &&     apt-get install -y --no-install-recommends ghc-8.6.5 cabal-install-2.4         zlib1g-dev libtinfo-dev libsqlite3-dev g++ netbase xz-utils make &&     curl -fSL https://github.com/commercialhaskell/stack/releases/download/v1.9.3/stack-1.9.3-linux-x86_64.tar.gz -o stack.tar.gz &&     curl -fSL https://github.com/commercialhaskell/stack/releases/download/v1.9.3/stack-1.9.3-linux-x86_64.tar.gz.asc -o stack.tar.gz.asc &&     export GNUPGHOME="$(mktemp -d)" &&     gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys C5705533DA4F78D8664B5DC0575159689BEFB442 &&     gpg --batch --verify stack.tar.gz.asc stack.tar.gz &&     tar -xf stack.tar.gz -C /usr/local/bin --strip-components=1 &&     /usr/local/bin/stack config set system-ghc --global true &&     /usr/local/bin/stack config set install-ghc --global false &&     rm -rf "$GNUPGHOME" /var/lib/apt/lists/* /stack.tar.gz.asc /stack.tar.gz' returned a non-zero code: 2
```

I searched the repo but couldn't find any instructions on how to build :cry:

**Comment by psftw** [comment]
sometimes keyservers can be wonky... what it should look like (which just worked for me):
```
... snip ...
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.rEwyNnGlg8/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys BA3CBA3FFE22B574
gpg: key BA3CBA3FFE22B574: 1 duplicate signature removed
gpg: key BA3CBA3FFE22B574: 3 signatures not checked due to missing keys
gpg: key BA3CBA3FFE22B574: 1 signature reordered
gpg: key BA3CBA3FFE22B574: public key "Herbert Valerio Riedel <hvr@gnu.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
... snip ...
```

**Comment by psftw** [comment]
Since I don't have a private repository with haskell library code, I'll need to create one for the purpose of testing/documenting this, which should be straight-forward using GitHub. The documentation could use a refresh anyway. I'll link to a PR here when it's ready to review if someone doesn't beat me to it :sweat_smile:  

https://github.com/docker-library/docs/blob/master/haskell/content.md

**Comment by TD5** [comment]
Thanks for getting this merged in! 😄

Can we justify a patch version bump for the official image (https://github.com/docker-library/official-images/blob/master/library/haskell) with this change included?

**Comment by Sir4ur0n** [comment]
Hey, I just tested building images again (8.6 and 8.8) on another machine, another distribution (MacOS vs Windows), another network, and I still get errors:
```
Running hooks in /etc/ca-certificates/update.d...                                                                    done.                                                                                                                Warning: apt-key output should not be parsed (stdout is not a terminal)                                              Executing: /tmp/apt-key-gpghome.svpyoyQg8r/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys BA3CBA3FFE22B574    gpg: keyserver receive failed: Server indicated a failure                                                            The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends gnupg ca-certificates dirmngr curl git &&     echo 'deb http://downloads.haskell.org/debian stretch main' > /etc/apt/sources.list.d/ghc.list &&     apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA3CBA3FFE22B574 &&     apt-get update &&     apt-get install -y --no-install-recommends ghc-8.6.5 cabal-install-2.4         zlib1g-dev libtinfo-dev libsqlite3-dev g++ netbase xz-utils make openssh-client &&     curl -fSL https://github.com/commercialhaskell/stack/releases/download/v1.9.3/stack-1.9.3-linux-x86_64.tar.gz -o stack.tar.gz &&     curl -fSL https://github.com/commercialhaskell/stack/releases/download/v1.9.3/stack-1.9.3-linux-x86_64.tar.gz.asc -o stack.tar.gz.asc &&     export GNUPGHOME="$(mktemp -d)" &&     gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys C5705533DA4F78D8664B5DC0575159689BEFB442 &&     gpg --batch --verify stack.tar.gz.asc stack.tar.gz &&     tar -xf stack.tar.gz -C /usr/local/bin --strip-components=1 &&     /usr/local/bin/stack config set system-ghc --global true &&     /usr/local/bin/stack config set install-ghc --global false &&     rm -rf "$GNUPGHOME" /var/lib/apt/lists/* /stack.tar.gz.asc /stack.tar.gz' returned a non-zero code: 2
```

Are you sure you don't have some specific, gitignored files on your local repo? This is suspiciously difficult to build this image 🤔 

Cheers!

**Comment by psftw** [comment]
@TD5 will create the bump PR today and link here.

@Sir4ur0n I'm sorry, the PGP key issue is a known problem -- check out https://github.com/docker-library/faq#openpgp--gnupg-keys-and-verification
I personally don't use any of the workarounds mentioned there, but I do split up the Dockerfile into multiple steps to utilize the cache when working on it. When the image is built by the official images team, they have the proxy hack in place. That's a pretty terrible answer, so I'll create an issue for this. I don't really want to directly embed the key in the image or split out the key retrieval into a separate step, but either of those would fix it and ATM is the best I can think of.

**Comment by Sir4ur0n** [comment]
Thanks for the heads up, appreciated. This sucks but seems to be out of your control, so no worries: Maybe this would be a nice addition to document that in the readme?

**Comment by psftw** [comment]
Closing this even though the upstream merge is not reviewed/deployed just yet, pending https://github.com/docker-library/official-images/pull/6831
