### ISSUE TITLE
Add 8.8.1, drop 8.4.x

### ISSUE THREAD

**Issue by psftw** [freebroccolo/docker-haskell#93]
GHC 8.8.1 released 25 August 2019 :tada: , so let's get a haskell:8.8.1 image released Soon (TM).

**Comment by GrahamCampbell** [comment]
I opened https://github.com/freebroccolo/docker-haskell/pull/92 11 days before you posted this issue. :P

**Comment by lag-linaro** [comment]
Yes please @psftw.

8.8.1 also has `aarch64` support so we can tackle #79 while we're at it.  \o/
