### ISSUE TITLE
New images availability

### ISSUE THREAD

**Issue by GrahamCampbell** [freebroccolo/docker-haskell#95]
When will the GHC 8.8 image be available on the Docker Hub please?

https://hub.docker.com/_/haskell?tab=tags

**Comment by psftw** [comment]
I just created https://github.com/docker-library/official-images/pull/6669 which is what actually defines the source of all the "official" images.  The official images team reviews the changes and executes some automated testing before merging and publishing the new image.

**Comment by GrahamCampbell** [comment]
Cool, thanks.
